version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      cargo:
        patterns: ["*"]
    open-pull-requests-limit: 10
