name: cargo-semver-checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
